### ISSUE TITLE
Wont open on win 10 

### ISSUE THREAD

**Issue by steven850** [VulpesSARL/LTOEnc#2]
Hi, when I run the .exe a CMD console opens and disappears within a half a second. 
Any ideas why it wont stay open?

**Comment by VulpesSARL** [comment]
the programm has no GUI, it's fully command-driven.
(you need to run a CMD as Admin separately and run the program in there, to see the supported parameters)

**Comment by VulpesSARL** [comment]
Closed issue - as it's not an issue
